export const DODO_PLANS = {
  lite: {
    name: "Lite",
    monthlyProductId: "pdt_0NVQ9rgRmOekcDhpDIGsS",
    yearlyProductId: "pdt_0NVQAOmJnJNJM3dIsd2Ac",
    monthlyPrice: 9,
    yearlyPrice: 99,
    leads: 100,
    features: [
      "100 verified leads/month",
      "Inbox delivery only",
      "Basic ICP matching",
      "- Industry selection",
      "- Company size selection",
      "- Location selection",
      "- Job titles (max 3)",
      "No CRM",
      "No Automations",
      "No Real-time Notifications",
      "No Advanced Analytics",
    ],
    featureAccess: {
      leadScraping: true,
      leadsPerMonth: 100,
      inboxDelivery: "inbox_only",
      icpMatching: "basic",
      crmAccess: false,
      crmIntegrations: false,
      automations: false,
      realtimeNotifications: false,
      advancedAnalytics: false,
      messageCrafting: false,
    },
  },
  solo: {
    name: "Solo",
    monthlyProductId: "pdt_0NVQA6iIOkZ8LTKFuaylJ",
    yearlyProductId: "pdt_0NVQAXRCbQ92oAIejS0NB",
    monthlyPrice: 29,
    yearlyPrice: 319,
    leads: 500,
    recommended: true,
    features: [
      "500 verified leads/month",
      "Inbox delivery with insights",
      "Advanced ICP matching",
      "- All Basic ICP features",
      "- Annual revenue filtering",
      "- Funding stage filtering",
      "- Multiple job titles (up to 10)",
      "- Custom ICP profiles (save up to 3)",
      "- Lead quality scoring",
      "Limited CRM",
      "Limited Automations enabled",
      "- Pre-built email automation",
      "- Pre-built WhatsApp automation",
      "- Pre-built social media automation",
      "- Up to 5 active automations",
      "Real-time Notifications",
      "Limited Advanced Analytics",
    ],
    featureAccess: {
      leadScraping: true,
      leadsPerMonth: 500,
      inboxDelivery: "inbox_with_insights",
      icpMatching: "advanced",
      crmAccess: true,
      crmIntegrations: "limited",
      automations: "limited",
      realtimeNotifications: true,
      advancedAnalytics: "limited",
      messageCrafting: true,
    },
  },
  pro: {
    name: "Pro",
    monthlyProductId: "pdt_0NVQAFTc6DAEBmEpHavd4",
    yearlyProductId: "pdt_0NVQAeAM8S260pmQn5Ekn",
    monthlyPrice: 69,
    yearlyPrice: 759,
    leads: 1500,
    features: [
      "1500 verified leads/month",
      "Inbox delivery with insights",
      "Advanced ICP matching",
      "- All Solo features",
      "- Unlimited saved profiles",
      "- Advanced matching algorithm",
      "- Match quality scores per lead",
      "- Priority scoring & ranking",
      "Full CRM",
      "All Automations enabled",
      "- All pre-built automations (email, WhatsApp, social media)",
      "- Unlimited active automations",
      "- Custom automation builder",
      "- Advanced triggers & actions",
      "Real-time Notifications",
      "Full Advanced Analytics",
    ],
    featureAccess: {
      leadScraping: true,
      leadsPerMonth: 1500,
      inboxDelivery: "inbox_with_insights",
      icpMatching: "advanced",
      crmAccess: true,
      crmIntegrations: "full",
      automations: "full",
      realtimeNotifications: true,
      advancedAnalytics: "full",
      messageCrafting: true,
    },
  },
};

export const getPlanByProductId = (productId: string) => {
  for (const [planKey, plan] of Object.entries(DODO_PLANS)) {
    if (plan.monthlyProductId === productId || plan.yearlyProductId === productId) {
      const billingCycle = plan.monthlyProductId === productId ? "monthly" : "yearly";
      return { planKey, ...plan, billingCycle };
    }
  }
  return null;
};
